# Site settings
title: Modi Granites Pvt. Ltd.
email: info@modigranites.com
description: > # this means to ignore newlines until "baseurl:"
  Modi Granites Pvt. Ltd., Established in the year 2012 is a young company by age, but vastly experienced in the
  granite field through its management. The promoters of Modi Granites Pvt. Ltd. have been associated with the
  industry for more than 20 years.
  here
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.modigranites.com" # the base hostname & protocol for your site
twitter_username: modigranites
port: 3000

gems:
  - jekyll-sitemap

exclude: [node_modules, gulpfile.js, _js] # Ignore _js folder as well so we only reload on js file change

# Build settings
markdown: kramdown
